# Generated by Django 5.2.6 on 2025-10-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="blog_image/%Y/%m/%d/"),
        ),
    ]
